-- Add column to track AI-generated images
ALTER TABLE public.meals 
ADD COLUMN IF NOT EXISTS is_ai_generated boolean DEFAULT false;

-- Add column to track AI image confirmation
ALTER TABLE public.meals 
ADD COLUMN IF NOT EXISTS ai_image_confirmed boolean DEFAULT false;

COMMENT ON COLUMN public.meals.is_ai_generated IS 'True if the meal image was generated by AI';
COMMENT ON COLUMN public.meals.ai_image_confirmed IS 'True if chef confirmed AI image represents their dish';