// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

function assertEnv(name: string, value: string | undefined) {
  if (!value || value.trim().length === 0) {
    // Fail fast so misconfigured deployments do not silently connect to wrong backends
    throw new Error(`[ENV] Missing ${name}. Check Lovable runtime env injection.`);
  }
}

assertEnv("VITE_SUPABASE_URL", SUPABASE_URL);
assertEnv("VITE_SUPABASE_PUBLISHABLE_KEY", SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
